### ISSUE TITLE
openPCDet install successed , but  bash of evaluation report not install

### ISSUE THREAD

**Issue by cynthia-you** [THU17cyz/3DIoUMatch#15]
Hi , there. Thanks for posting such a  amazing work.
When run installment of openpcdet , it installed successfully:
```
Using /home/fusion/miniconda3/envs/3Dmatch/lib/python3.7/site-packages
Finished processing dependencies for pcdet==0.3.0+0
```
But when i preform the evaluation, the problem i encountered is:
```
Traceback (most recent call last):
  File "/home/fusion/project/3DIoUMatch/utils/box_util.py", line 18, in <module>
    from pcdet.ops.iou3d_nms.iou3d_nms_utils import boxes_iou3d_gpu
ModuleNotFoundError: No module named 'pcdet.ops.iou3d_nms.iou3d_nms_utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from models.votenet_iou_branch import VoteNet
  File "/home/fusion/project/3DIoUMatch/models/votenet_iou_branch.py", line 18, in <module>
    from models.grid_conv_module import GridConv
  File "/home/fusion/project/3DIoUMatch/models/grid_conv_module.py", line 12, in <module>
    from utils.box_util import rot_gpu
  File "/home/fusion/project/3DIoUMatch/utils/box_util.py", line 20, in <module>
    raise ImportError("please first install pcdet according to README.md")
ImportError: please first install pcdet according to README.md

```
Could you please tell me is there something i can do to fix it. THX~

**Comment by yezhen17** [comment]
Hi @cynthia-you ,

Thanks for your interest in our work! Can you try

```
cd OpenPCDet
rm -rf ./build
find . -name "*.so" | xargs rm
```

And then install pcdet again?

**Comment by cynthia-you** [comment]
还是不行 不知道是不是因为虚拟环境和系统的gcc问题 我再配一下 。  谢谢~

**Comment by yezhen17** [comment]
Yes, I think that is possible. One solution is to install the complete OpenPCDet following the extensive instructions. 不客气！~
